name: Schedule Script

on:
  schedule:
    - cron: 0 0 * * *  # 每天凌晨 0 点执行

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          python pdx.py
